services:
  app:
    build: .
    volumes:
      - .:/go/src/

  db:
    image: 'postgres:9.6'
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: encoder
    volumes:
      - .pgdata:/var/lib/postgresql/data

  rmq:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
