services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      filebeat_collector: true

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_DATABASE: micro_videos
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  rabbitmq:
    build: ./.docker/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
